export default {
  en: {
    "0": "Unlimited Access to All Features",
    "1": "Unlimited documents",
    "2": "Count mode",
    "3": "Text recognition (OCR)",
    "4": "Monthly",
    "5": "per month",
    "6": "3 DAYS FREE",
    "7": "month",
    "8": "Annually",
    "9": "per year",
    "10": "MOST POPULAR",
    "11": "Continue",
    "12": "Auto-renewable. Cancel anytime.",
    "13": "Terms of Use",
    "14": "Restore",
    "15": "Privacy Policy",
    "16": "Export to clouds"
  },
  es: {
    "0": "Acceso ilimitado a todas las funciones",
    "1": "Documentos ilimitados",
    "2": "Modo de recuento",
    "3": "Reconocimiento de texto (OCR)",
    "4": "Mensual",
    "5": "por mes",
    "6": "3 DÍAS GRATIS",
    "7": "mes",
    "8": "Anual",
    "9": "por año",
    "10": "LO MÁS PEDIDO",
    "11": "Continuar",
    "12": "Renovable automáticamente. Cancela cuando quieras.",
    "13": "Términos de uso",
    "14": "Restablecer",
    "15": "Política de privacidad",
    "16": "Exportar a las nubes"
  },
  fr: {
    "0": "Accès illimité à toutes les fonctionnalités",
    "1": "Documents illimités",
    "2": "Mode décompte",
    "3": "Reconnaissance de texte (OCR)",
    "4": "Tous les mois",
    "5": "par mois",
    "6": "3 JOURS GRATUITS",
    "7": "mois",
    "8": "Tous les ans",
    "9": "par an",
    "10": "LE PLUS POPULAIRE",
    "11": "11r",
    "12": "Renouvelable automatiquement. Annulez à tout moment.",
    "13": "Conditions d'utilisation",
    "14": "Restaurer",
    "15": "Politique de confidentialité",
    "16": "Exporter vers les nuages"
  },
  ja: {
    "0": "全ての機能へ 無制限アクセス",
    "1": "無制限のドキュメント",
    "2": "カウントモード",
    "3": "テキスト認識 (OCR)",
    "4": "月次",
    "5": "/月",
    "6": "3日間無料",
    "7": "か月",
    "8": "年次",
    "9": "/年",
    "10": "一番人気",
    "11": "続行する",
    "12": "自動更新可能。いつでもキャンセル可能。",
    "13": "利用規約",
    "14": "復元する",
    "15": "プライバシーポリシー",
    "16": "クラウドへのエクスポート"
  },
  nl: {
    "0": "Onbeperkte toegang tot alle functies",
    "1": "Onbeperkt aantal documenten",
    "2": "Aantal modus",
    "3": "Gratis tekstherkenning (OCR)",
    "4": "Maandelijks",
    "5": "per maand",
    "6": "3 DAGEN GRATIS",
    "7": "maand",
    "8": "Jaarlijks",
    "9": "per jaar",
    "10": "MEEST POPULAIR",
    "11": "Doorgaan",
    "12": "Automatisch verlengbaar. Altijd annuleren.",
    "13": "Gebruiksvoorwaarden",
    "14": "Herstellen",
    "15": "Privacybeleid",
    "16": "Export to clouds"
  },
  ru: {
    "0": "Неограниченный доступ ко всем функциям",
    "1": "Любое количество документов",
    "2": "Режим «Подсчет»",
    "3": "Распознавание текста (OCR)",
    "4": "1 месяц",
    "5": "в месяц",
    "6": "3 ДНЯ БЕСПЛАТНО",
    "7": "месяц",
    "8": "1 ГОД",
    "9": "в год",
    "10": "ПОПУЛЯРНОЕ",
    "11": "Продолжить",
    "12": "Автопродление. Отмена в любое время.",
    "13": "Условия использования",
    "14": "Восстановить",
    "15": "Конфиденциальность",
    "16": "Экспорт в облака"
  },
  zh: {
    "0": "无限制使用 所有功能",
    "1": "文档无限制",
    "2": "计数模式",
    "3": "文本识别（OCR）",
    "4": "每月",
    "5": "每月 ",
    "6": "3日免费",
    "7": "月",
    "8": "包年",
    "9": "每年",
    "10": "最热门",
    "11": "继续",
    "12": "自动续订。可随时取消。",
    "13": "使用条款",
    "14": "恢复",
    "15": "隐私政策",
    "16": "导出到云端"
  }
}