import Layout from "./script/Layout.js";
import Translate from "./script/Translate";
import Tariffs from "./script/Tariffs.js";
import global from "./styles/global.css";
import offer from "./styles/offer.css";
import button from "./styles/button.css";
import tariffs from "./styles/tariffs.css";
import corp from "./styles/corp-info.css";
import features from "./styles/features.css";